# # From https://tomasfarias.dev/posts/sphinx-docs-with-poetry-and-github-pages/
# name: Docs2Pages
# on:
#   push:
#   pull_request:
#     branches:
#       - main
#
# jobs:
#   build-docs:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2
#       with:
#         fetch-depth: 0
#     - uses: actions/setup-python@v3
#       with:
#         python-version: 3.9
#     - uses: abatilo/actions-poetry@v2.1.3
#     - name: install
#       run: poetry install -E docs
#     - name: Build documentation
#       run: |
#         mkdir gh-pages
#         touch gh-pages/.nojekyll
#         cd docs/
#         poetry run sphinx-build -b html . _build
#         cp -r _build/* ../gh-pages/
#     - name: Deploy
#       if: ${{ github.event_name == 'push' }}
#       uses: peaceiris/actions-gh-pages@v3
#       with:
#         publish_branch: gh-pages
#           #folder: gh-pages
#         publish_dir: _build
#         force_orphan : true
#
# on: [push]

jobs:
  build:
    name: Sphinx Pages Test
    runs-on: ubuntu-latest
    steps:
      - uses: seanzhengw/sphinx-pages@master
        id: sphinx-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_readme: true
